// import "./globals.css"
// import Header from "./_components/header"
// import Footer from "./_components/footer"

// export const metadata = {
//   title: "Creative Supply",
//   description: "Generated by Leonard Sianipar",
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Header />
//         {children}
//         <div className="relative">
//           {/* <img src="/shape/half-circle.png" alt="11" className='absolute right-0 bottom-[300vw] h-[24vw] opacity-80 -z-10' />
//           <img src="/shape/half-circle.png" alt="11" className='absolute right-0 bottom-[20vw] h-[24vw] opacity-80 -z-10' />
//           <img src="/shape/half-circle.png" alt="11" className='absolute -left-[4vw] bottom-[140vw] h-[24vw] opacity-50 z-10 rotate-180' />
//           <img src="/pic/phone.png" alt="11" className='absolute right-0 bottom-[90vw] h-[34vw] z-10 animate-bounce1' /> */}
//         </div>
//         <Footer />
//       </body>
//     </html>
//   )
// }


import "./globals.css"
import Header from "./_components/header"
import Footer from "./_components/footer"

export const metadata = {
  title: "Creative Supply",
  description: "Generated by Leonard Sianipar",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
